--- 
title: "Response to reviewers"
author:
  - "Milad Memarzadeh"
  - "Carl Boettiger"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
bibliography: citations.bib
---




ASSOCIATE EDITOR'S RECOMMENDATION

Dear Professor Bronstein; Prof Dwyer,

> My recommendation is that manuscript 57722 be declined without prejudice.   The authors use a state of the art computer algorithm known as ``POMDP'' to determine, on the fly, how fisheries should be managed, in terms of the total amount of stock that can be harvested, and the profit accruing from that harvest.   This is an important problem in ecology, and the authors approach appears to offer significant insight.  The reviewers nevertheless point out some important ways in which the text could be improved, and reviewer 1 in particular argues that the authors's approach may be significantly flawed.  These problems would therefore need to be addressed for a revision to be successful.

We appreciate the careful and constructive comments of the editor and reviewers, which have allowed us to re-write the manuscript to address each of the issues raised here. 

Reviewer 1's primary objection essentially re-asserts the "paradox of measurement uncertainty" that previous literature has also asserted: that uncertainty should somehow make less cautious.  We appreciate the reviewer highlighting the importance of explaning this central issue properly, and our revisions should make it clear how this erroneous and potentially dangerous conclusion arises from simplifying assumptions.  Reviewer 2's primary objection is the missed opportunity of focusing too narrowly on fisheries.  We agree entirely with the reviewer that the fundamental issues here are germane to ecological management and not specific to fisheries, and have revised the presentation substantially to address this.  Both reviewers raised concerns about the clarity of the methods; so in addition to rewritten discussion of methods we now provide fully executable code to replicate the analysis shown here.  Lastly but most importantly, both reviewers raise the observation that few fisheries are actually managed using a strict constant escapement (CE) policy.  We have introduced more realistic management strategies based on regulating fishing mortality through maximum sustainable yield (MSY) and total allowable catch (TAC), as additional comparisions.  TAC illustrates a different, more heuristic approach to uncertainty than seen in the optimal control methods that provides some valuable additional insights into the challenge of accounting for measurement error. We think this results in a much more interesting mansucript which should be relevant to the broad audience of the American Naturalist.

Below we provide more detailed responses to each of the concerns raised and how they have been addressed in this revision.  

> One of Reviewer 2's main comments is that the article focusses too narrowly on fisheries and stock assessment, and the Reviewer argues that the authors could instead frame their work more broadly in terms of applied ecology in general, perhaps by citing problems of measurement uncertainty in other applications besides fisheries.  These points are very well taken, especially given that The American Naturalist covers biological problems in a very broad sense.   For the work to be of general interest to the readership of The American Naturalist, the authors would therefore have to explain more clearly the relevance of their work to applied ecology in general.


We now emphasize that making decisions in face of imperfect information is by no means an issue isolated solely to fisheries, which merely serves as a concrete example where relevant data can be easily obtained.  We also note that fisheries management has long been a crucible in which ecological management theory and practice has been forged before becoming widely applied in other ecological contexts. 

> Reviewer 1 in contrast makes a  specific and detailed comment about a very particular issue.   In discussing this comment, an important point is that I am sufficiently far from being a fisheries biologist that I am not entirely understand sure that I understand the objection, emphasizing the importance of Reviewer 2's comment that The American Naturalist is a general interest journal, not a fisheries journal.  This caveat aside, my understanding of Reviewer 1's comment is that the Reviewer ran a set of simulations which were essentially the same as in the manuscript, except that the Reviewer explicitly excluded the possibility of 90 percent harvest of the stock population. 

The analysis of Reviewer 1 is very interesting, and finds essentially the same paradoxical result as earlier published studies (e.g. @Clark1986; @Sethi2005); as the reviewer summarizes:

> In every case the optimal escapement goal was lower when observation error was included. 

This is a paradoxical conclusion that defies the precautionary principle, and as such would have important ramifications in ecological management in many applications beyond fisheries.  Further, though the reviewer's analysis is not identical to either the approaches of @Clark1986 or @Sethi2005 (neither assume constant escapement and both find this paradoxical result in only some but not all cases), we believe our analysis provides both a refutation of this result and a clear intutition as to where this misleading conclusion has come from.

As the editor notes, we suspect that Reviewer 1's simulations are not indeed identical except in the way mentioned, since they appear to assume the optimal policy can be specified in terms of a single constant escapement. Our results and in general escapement need not be constant but will depend on the observed stock size an on previous measurements, as we now emphasize.  Also as the editor notes, the Reviewer's description of what they have done is extremely brief and thus difficult to be sure we have characterized precisely, but nevertheless, we believe our analysis sheds some light on why the reviewer finds this paradoxical conclusion while our analysis does not.  

The escapement recommended by our POMDP solution is not constant, but depends both on prior information and the current estimate of the stock size, as illustrated in Figure 4.  Assumptions that simplify the calculation of the policy by ignoring these aspects can thus reach different conclusions.  @Clark1986 assumes that the stock size is known perfectly at the end of the prior period, @Sethi2005 implicitly assumes that the prior belief is always uniform rather than reflecting previous measurements, which puts erroneous probability weight on the chance the stock is in fact very high.  

Figure 4 offers a clear explanation for when it is optimal to increase harvest in response to increased uncertainty: the POMDP harvest only exceeds the CE harvest when the measured stock size is erroneously low.  That is, when the prior belief would have suggested the observation should be much higher, and therefore the measurement is most likely an error under-estimating the true stock size.  This logic is entirely intuitive and is bourne out in the resulting POMDP policies. 

>  In the reviewer's simulations, the optimal escapement level is lower in the presence of measurement error, whereas in fig. 5 of the manuscript,  the optimal escapement level is instead higher in the presence of measurement error.  Reviewer 1's description of their simulations is brief enough that I would not expect the authors to build their entire revision around an effort to respond to this comment.   If the authors have indeed allowed for 90 percent harvest, however, it is important that they test whether their results are different if they place an upper limit on the fraction of the stock that they allow to be harvested.  

The reviewer and editor have raised an important issue in the question of whether we permit the harvest quota to be set to a value higher than the stock.  There are two problems with this.  First, it's not clear how the reviewer implements this assumption in the face of measurement uncertainty: how can one be certain a quota is less than 90% of stock size X without knowing what X is?  One can obviously enforce this with respect to the measured stock size but not the true stock size.  More importantly, this assumption amounts to the assertion that it is mathematically impossible to overfish a stock to the point of collapse.  However low the stock size might get, local extinction is impossible.  In this world-view, there will always be some tiny fraction of ato-fishes from which the population can recover.  Assuming that local extinction is impossible will indeed bias any optimal decision model to be more agressive.  Obviously this also has impliciations for ecological models in general, conservation policy would look different if we assumed extinction was impossible. @Clark1986 already recognized that a very similar assumption in @Reed1979 derivation that stochastic models needed no additional caution ($S=D$) was likely due to the fact that accidentally extinction was impossible (see manuscript, line 150). We do not adopt this assumption.  Obviously real world populations cannot be indefinitely reduced by only a fractional percentage. In our simulations, though we consider a Ricker model, stock abundances are divided into 100 distinct bins, with the smallest bin corresponding to a stock size of zero. Thus it is possible for overharvesting or stochastic environment, or some combination of both, to lead a population to permanenently collapse once it has gotten small enough.  


> I also agree with Reviewer 1's comment that the methods are not that easy to follow.  That said, to my understanding, the escapements in fig. 2 are not constant, and so Reviewer 1's comment that a constant escapement cannot lead to the collapse of a stock seems to me to be irrelevant, but again I may be wrong, and my uncertainty emphasizes the lack of clarity in the writing, especially with respect to the Methods.   

We agree entirely with this, and hope that the rewritten description, together with complete code, helps make this somewhat clearer.  


> Page 8-12 in particular are written in a very formal style that I associate with journals that focus on mathematics rather than on biology, with the difficulty problem that much of this text has small grammatical errors that exacerbate the clarity problem.  Meanwhile, both Reviewers argued that the authors have not accurately characterized the literature in this area, and that problem would also have to be solved in a revised version.

The presentation of all of this material has been entirely re-written in what we hope you will find is a much more appropriate and accessible style.  To avoid needless formalism, we do not rehash the technical details of solving Partially Observed Markov Decision Processes but instead point to the extensive literature already existing on the subject.  Instead, we focus on describing the nature of the problem and how it differs from analyses such as the perfectly observed Markov Decision Process that provides the basis for the Constant Escapement strategy (@Reed1979) and from other Bayesian hierarchical modeling (e.g. partially observed Markov processes, pomp, or Hidden Markov Models, HMMs) which are not decisison processes at all, but rather a prerequiste part of choosing & paramaterizing a model, not using said model to make a decision.  

> In spite of these negative comments, it seems like the overall approach has a great deal of potential, as Reviewer 2 argues, and if Reviewer 1's concerns prove to be minor, then I believe that a revised version would be a substantial contribution.  That said, the complexity of the technical issues is quite high, and so it may be simpler to submit the manuscript to a journal that specializes in mathematical biology or in fisheries management.

Greg Dwyer


xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Reviewer #1:

For complete review, see the attached PDF, which begins as follows:

> I attempted to evaluate the papers overall conclusions by a very simple simulation and these results
seem to challenge the papers conclusions.
I simulated a population with the model the authors describe with both observation and process error
lognormally distributed and using the authors parameters. For a range of escapement goals I calculated
the net present value of using that escapement goal, and compared the consequences when there was
no observation error to the case where the lognormal cv was 0.5 – that is very high observation error.
The one difference I made was I did not let the harvest exceed 90% of the total population size ... this
seems reasonable as I know of few fisheries where 90% of the population could be harvested in a single
year.

> The graph below shows a typical result. The thin line is with no observation error, the ticker line with the observation error. In every case the optimal escapement goal was lower when observation error was included.

We thank the Reviewer for this careful parallel investigation, which was very useful in focusing the manuscript on some of the key results.  We believe the differences in our respective results can be explained by the differences in our methods as discussed in our reply to the Editor's discussion of this issue. In short, we believe the reviewer's seemingly counter-intuitive result that increased uncertainty should be met with an action (lowering escapement) that would increase the risk of stock collapse rather then the intuitive response to be cautious by reducing harvest, is simply an artefact of the reviewer's assumption that stock collapse is impossible, and thus increased harvesting poses no real risk. 


> I can’t really understand some of the results in the paper ... for instance I don’t see how a fixed
escapement policy could lead to the collapses shown in Figure 2 – using fixed escapement policies you
can’t have you population continue to decline.

We agree that the results and methodoloy could have been much more clearly presented. We hope the rewritten presentation of these results clarifies these issues. In particular, note that once you introduce measurement error a fixed escapement policy can only achieve a fixed *expected* escapement, you never know what the actual escapement is because you never know exactly how many fish you started with.  As measurement errors are equally likely to be too high or too low, a run of "heads", so to speak, would result in consistently overharvesting and continued decline (see discussion around line 363.)


> Finally it is certainly not true that fixed escapement policies are commonly used. To my knowledge
almost all marine fish populations are managed with policies more resembling fixed harvest rates with
caveats that target harvest rate declines when stocks drop below a target stock size. Certainly some
salmon stocks are managed with an escapement goal, but they are not in any sense common or the
default in marine fisheries management.

The reviewer is entirely correct about this, and we greatly appreciate the reviewer raising this important issue.
In addition to the previous analysis which focused only on comparison to a constant escapement policy, we now
also include comparisons to a more realistic "Total Allowable Catch", or TAC strategy.  



xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Reviewer #2:

> In this clearly written paper the authors show that fish population dynamic models that ignore measurement error can result in significant overharvesting, decreased economic returns, and the potential for complete collapse of the stock. The key advance is the use of an algorithm for partially observed Markov decision processes (POMDP) to provide a complete solution rather than relying upon inferences from a deterministic model or a model of optimal control that does not update belief states during each time step.


> The treatment of this issue is remarkably comprehensive with respect to structural uncertainty of the model formulation. In fact, the authors in some way bury what I see as the lead in the Appendix. They include analysis of a population subject to an Allee effect, and produce the same general conclusion as they do via analysis of models with more standard dynamics: the POMDP approach is less likely to cause overharvest and population collapse than alternative approaches, even if the location of the unstable steady state population size (tipping point) is unknown. This finding is very important given the increasingly voluminous literature on thresholds and tipping points, suggesting that proper accounting for measurement uncertainty may be a practical alternative to investing more in reducing such uncertainty in the budget-constrained world of natural resource management.


> As is clear from my summary, this paper is framed for a narrower audience focused on fisheries and stock assessment. To draw in a broader readership, I suggest that the authors motivate the problem they address and interpret their results in the context of the more general ecological, wildlife, and forestry literatures. Specific examples of how measurement uncertainty has been found problematic in fisheries and wildlife assessments would be helpful.

We thank the reviewer for this careful and constructive review, and agree entirely with the recommendation that the fundamental issues here are not limited to the problem of fishing quotas butare germane to much of ecological decision making. We have now tried both to set up the generic nature of the issue of measurement uncertainty (see Introduction) and discuss its implications beyond fisheries much more explicitly (e.g. lines 423 - 437).  We have however removed the treatment of the tipping point model in order to focus explicitly on the role of uncertainty in the more familiar case of logistic growth, where the dramatic consequences of measurement uncertainty may be less inutitive and cannot be dismissed merely by questioning the frequency of tipping points occurring in real systems.  We hope to address the problem of tipping points more explicitly and more fully in later work.

> The authors mischaracterize the extent to which measurement uncertainty is left untreated in stock assessments. Dichmont et al. 2016 (Fisheries Research) provide a nice review of how some of these measurement uncertainty issues are treated in practice in US stock assessments, and an entry point to the literature. If the authors intend to focus on theoretical models and general solutions for population dynamics, their assertion about failure to incorporate measurement uncertainty completely may be valid but this should be clarified.

We had no intention of suggesting that measurement uncertainty was under-represented in *stock assessments*; indeed it is precisely the *prevalance* with which stock assessment models account for uncertainty that motivates this work.  We have extensively revised the manuscript to be much clearer on this point.  Our assertion is that these estimates of the uncertainty associated with a measurement of the stock size to which the reviewer refers are not properly accounted for in the process of setting a quota.  


> Unlike the classic pretty good yield paper mentioned in the paper (line 440), the authors do not adequately address how conservative harvest is likely to be met with opposition by harvesters and how this issue can be addressed directly by their analysis. 


This is an excellent point which we now develop in the discussion, lines 456-470.


> Similarly, rather than dismiss management strategy evaluation as a less preferable alternative to the optimal control approach taken here, it would be nice to see the authors include a formal contrast. Might the offline POMDP approach be framed this way and results inferred without additional analyses? This would be nice because in the real world, optimal control with annual updating of harvest regulations (the POMDP approach) may not practical. The offline POMDP seems more realistic, perhaps with an online phase implemented such that belief states could be updated in 5-10 year intervals.

We now include a formal comparison against TAC-based management policy (and also MSY based policy in the supplement), which reflect this aspect of today's actual management polcies which are not updated annually but apply a constant fishing effort (mortality). We also discuss several of the practical objections to implementing POMDP in practice and how it might be modified to address more of these concerns, e.g. lines 456-490.  
 

> Minor comments:
The analysis related to Fig 5 made me wonder how POMDP compares to alternative frameworks when a stock is increasing or decreasing in abundance. The authors mention this in their interpretation, but I think it could be highlighted more as it seems that the POMDP approach (at least for plaice) allows a more careful tracking of catch to stock size during collapse and rebuilding, a result that would be viewed favorably by fishermen and conservationists alike.

Excellent observation! Yes, due to the influence of the prior belief, POMDP is slightly more catious when a stock is rebuilding from small sizes

> Some reorganization may be warranted. Several portions of the Results section describe Methods, which would be nice to signal earlier in the MS (e.g., lines 266-281, lines 298-300 and lines 321-324 could be included in Methods to clarify that the POMDP overestimates measurement uncertainty, etclines 348-351, etc).

We agree entirely, and now present the full discussion of the methods and models before going into the results.  

> In several places the authors use loose language by referring to marine ecosystem dynamics when in fact they are treating population dynamics.

Agreed, this has been addressed in the rewrite. 

> The authors discuss volatility of different solutions and would be served well to quantify it. E.g., lines 365-369

We believe this is much better illustrated by the visualization of these solutions in Figure 5, and introducing a statistic to quantify this would only needlessly confuse that discussion. 

