---
title: "The importance of measurement uncertainty in ecological management"
author:
  - name: "Milad Memarzadeh"
    affiliation: a
  - name: "Carl Boettiger"
    affiliation: a, 1
address:
  - code: a
    address: "Dept of Environmental Science, Policy, and Management, University of California Berkeley, Berkeley CA 94720-3114, USA"
  

abstract: |
  We settle a long standing paradox in ecological management regarding the influence of measurement uncertainty.  Previous work has frequently suggested that the optimal management of fisheries should respond to increased measurement uncertainty by increasing harvest effort, contrary to the intuition of the precautionary principle. Through the use of cutting-edge point-based POMDP methods, we demonstrate that the standard management theory which ignores measurement uncertainty may lead to over-exploitation of fisheries and increased probability of economic and ecological collapse.  In contrast, POMDP solutions which account for measurement error are overall more conservative, avoiding over-exploitation while generating higher economic value. 


keywords:
  - Measurement uncertainty
  - POMDP
  - Decision theory
  - Fisheries
  - Conservation

lineno: true

bibliography: citations.bib
output: rticles::elsevier_article
---

Imperfect information is ubiquitous in ecological management and conservation decision making. While the pressing concerns of global change have put the spotlight on forecasting, i.e. the uncertainty of the future [@Petchy2015], management decisions must also contend with uncertainty of the present: How many fish are in the sea today? What regions harbor the most fragile biodiversity? How have invasive species transformed native communities? A recognition of the importance of uncertainty as well as sophisticated methods and tools to do so has become increasingly widespread in the context of estimating ecological models from available data, thanks in large part to the rise of approaches such as Hierachical Bayesian Modeling, along with convenient software tools for implementing these methods.  In sharp contrast to that shift, the treatment of uncertainty in *decisions* -- how the uncertainty in models should be reflected in scientific recommendations, remains far less developed, more qualitative, and underserved by available tools.  In this paper we illustrate how uncertainty in measurement has a dramatic negative impact on outcomes under a variety of these exsiting approaches, which can be avoided through the use of more formal approaches that have since been developed in other fields that can likewise be implemented in software tools.

Approaches for decision making under uncertainty in ecological systems can be divided into two camps: approaches based in "optimal control" and usually favored by natural resource economists, and approaches based in heuristic methods such as scenario planning, resilience thinking, and precautionary rules of thumb, more commonly found in both ecological literature and actual practice [@Fischer2009; @Polasky2011].  While researchers have for some time recognized the need to unify the transparent and quantitative algorithmic approach of optimal control with the greater complexity and uncertainty of real ecosystems that is acknolwedged by heuristic methods, computational barriers to doing so have hither-to stymied this progress.  Here, we illustrate how the limitations of these approaches has been manifested in the example of fisheries management, and present a new approach that can combine the reality of measurement uncertainty and the rigour of optimization to resolve a long-standing paradox and suggest a more robust approach to management.   

The area of fisheries conservation and management has long been both a crucible and proving ground for the theory of ecological management, including topics such as adaptive management [@Walters], ecosystem-based management [@Levin2008] to resilience thinking [@Holling; @May] and back to the birth of resource economics [@Beverton; @Scheffer], thanks to its global relevance, long history, and readily available data.  Consequently, understanding the impact of measurement uncertainty in this rich and well-studied context will have implications for both resource management and conservation efforts in other domains, many of which draw on concepts established or tested in fisheries ecosystems.  We compare the results of managing simulated fish stocks under the existing optimal control approach, a heuristic approach that more closely resembles today's management practices, and a newly proposed approach that provides a more rigorous treatment of uncertainty.

## Methods

We consider the management problem of setting catch quotas for a marine fishery in the face of imperfect information about the current stock size and uncertainty about future recruitment.  To facilitate tractability and intepretation, we will consider a simple and well-studied model of population growth (stock recruitment) in marine fisheries, the Graham-Schaefer model:

Though this and very similar models are widely used in large scale analyses across diverse stocks (e.g. [@Costello2016; @Britten2017]), and common in other conservation contexts where richer models are unavailable, neither the existing approaches nor the one we introduce here are limited to such one-dimensional stochastic models with known parameters. In practice, this model may include age or stage structure and will reflect uncertainty not only in the stochastic recruitment but in the parameters themselves, usually as the result of a heirarchical model estimation process.   All that is required of the model is that it defines the probability of transitioning to a new state given the current state (here, simply the stock size) and the action taken (here, just the harvest).  Uncertainty either in the parameters, in the model, or inherent in the stochastic process can all be reflected in such probabilities. 

Each year, the manager also obtains an estimate $y_t$ of the true $x_t$ stock size, 

$$y_t = Z_m x_t$$
for some measurement error $Z_m$.  Given the estimated recruitment model along with this estimate of the stock size, the manager must set a harvest quota $h_t$ for that year.  The methods we consider here all differ primarily in their handling of these uncertainties. If this system were completely deterministic so that there was no uncertainty, all would produce identical long term policies and thus achieve identical outcomes.  

In the case of no uncertainty, the optimal harvest strategy is to reduce the population to the size at which it obtains the maximum growth rate, known as Biomass at Maximum Sustainable Yield, $B_{MSY}$ (this is adjusted slightly in the case of economic discounting of future profits, but is otherwise quite general, see @ClarkTextbook). For the Graham-Schaefer model (and many others), this is achieved at $B_{MSY} = K/2$, with a corresponding annual harvest of $H_{MSY} = r K / 4$.  

This equilibrium analysis says nothig about the appropriate harvest at stock sizes above or below $B_{MSY}$, which highlights some essential differences between the optimal control policy and more typical fisheries management.  The optimal policy is impatient: it seeks to achieve the optimal yield as quickly as possible.  Below $B_{MSY}$, the economically optimal thing to do is to completely shut down the fishery, while above this stock, a harvest greater than $H_{MSY}$ can be optimal for that year.  This strategy is known as "constant escapement," since a constant sock size $B_MSY$ escapes harvest each year.  In practice, it is more common to pursue a policy of constant fishing effort (fishing mortality), $F_MSY = H_MSY / B_MSY$.  Continuing to harvest at $F_{MSY}$ when a stock is above or below $B_{MSY}$ is economically inefficient and causes depleted stocks to rebuild more slowly, but, in the absense of uncertainty, ensures a return in the long run to stock sizes of $B_MSY$ and harvests of $H_{MSY}$.  These differences will be important in understanding how these approaches perform once uncertainty is introduced.  

## Pardoxes of uncertainty

The literature of optimal harvests under uncertainty is one of paradoxes, which can only be resolved by a more comprehensive treatment of measurement uncertainty.  

### Reed's Paradox: $S = D$

The first of these we shall refer to as Reed's Paradox, owing to the mathematical proof provided in @Reed1979 which demonstrates that, under sufficiently general assumptions, the optimal escapement $S$ for a population under stochastic growth, is identical to the optimal escapement $D$ of a deterministic population, $S = D = B_{MSY}$.  This suprising result suggests that in going from a world where a manager has perfect knowledge of absolutely everything into a scenario where the manager faces considerable uncertainty about the future state of the world, no additional precaution is needed.  This also provides the manager with a remarkably convenient mechanism for determining the optimal harvest policy: rather than rely on computationally intensive Stochastic Dynamic Programming to determine the optimal policy, a simple derivative will suffice, which is all that is needed to solve the maximum of the deterministic problem.  

### Clark's Paradox: $M < D$

@Clark1987 was among the first attempts to resolve Reed's Paradox. @Clark1987 (quite correctly, as we will see), identified the crux of Reed's Paradox as the absence of measurement uncertainty:

> An important tacit assumption in Reed’s analysis, as in the other works referred
to above, is that the recruitment level X is known accurately prior to the harvest decision, [...] In the case of fishery resources, the stock level X is almost never known very accurately, owing to the difficulty of observing fish in their natural environment.

Unfortunately, @Clark1987 was unable to solve the resulting problem exactly, but had to adopt an almost equally troublesome assumption:

> For reasons of tractability, we shall adopt the simplifying assumption that the escapement level S, is known exactly at the end of that period. (The mathematical difficulty
of the problem increases markedly if this assumption is
relaxed.) 

The resulting solutions only deepened the paradox, rather than recovering a more cautious policy in response to the uncertainty, @Clark1987 finds policies that are often *less* cautious:

> [Our] results appear to contradict the conventional wisdom of renewable resource management, under which high uncertainty would call for increased caution in the setting of quotas.

Using different but still implicitly approximate results nearly two decades later, @Sethi2005 largely confirm Clark's Paradox, which they likewise observe with some concern:

> It may seem counter-intuitive that a measurement error causes lower expected escapements below the deterministic fishery closure threshold.

While other attempts to introduce measurement error have been considered, each relies on various approximations that similarly alter the problem, such as assuming the solution must be of 'constant-escapement' type [@.....].  

## Uncertainty in practice

Fortunately, management practice has so far ignored this paradoxical suggestion that uncertainty should be met with greater rather than reduced fishing quotas.  Instead, most well-managaged fisheries operate on rules that are more the result of common sense than mathematical optimization.  While details differ, the basic approach can be thought of as starting with the deterministic notion of $B_{MSY}$ and corresponding optimal fishing level $F_{MSY}$ as a way of determining an Overfishing Limit, (OFL), which is then adjusted to some lower level, Allowable Biological Catch (ABC) to reflect uncertainty in the stock assessment.  ABC is then adjusted lower once again, to determine a Total Allowable Catch, (TAC), reflecting uncertainty in reported catch or other uncertainty.  





------

A fundamental concept to the management of any natural population is the notion of Maximum Sustainable Yield, MSY. The notion of MSY is rooted in the determinstic models dating back to foundational work in resource economics and ecological management half a century ago [@Berverton; @Scheffer].  Though the concept has been the focus of significant criticism for some time [e.g. @Botsford_nature_piece] that ctitique has been largely on the "Maximum" part, while the existence of a "Sustainable Yield."  

## Reed's Paradox: $S = D$

In 1979, a fundamental paper by William Reed [@Reed1979] proved that, under a very general assumptions, the harvest policy for a stochastically fluctuating population was identical to that of the equivalent, deterministic population.  More precisely, Reed shows that the optimal harvest of the stochastically flutuation population should always aim to reduce the population back to a constant size $S$ (termed by Reed as "escapement," while in most fisheries literature uses the term $B_{\text{MSY}$, the biomass at Maximum Sustainable Yield}).  Moreover, this value, $S$, is no more conservative than had we been able to predict future populations with perfect accuracy, as in the determinstic case of constant escapement, $D$.  A notable exception to this result is when the population is not "self-sustaining," that is,
the stochasticity is severe enough to pose an extinction risk to the unhavested population.  In such cases Reed proves there is still a single constant target population size $S$, but that $S > D$, though often by very small amount, reflecting the small probability of a purely chance extinction.  

An important corrolary of this result is that suggested a way to side-step the laborious dynamic programming required to find an optimal policy for stochastic populations: the deterministic solution is found trivially from maximum of the stock-recruitment curve. Thus much subsequent attention has focused on the estimating stock-recruitment, including methods that address considerable uncertainty in the data used for this estimate [@], while largely ignoring the subsequent step of how to determine an optimal policy in light of that uncertainty. 

The lack of any intuitively precautionary response to the introduction of uncertainty did not go unnoticed: in 1986 Clark and Kirkwood first pointed to the absence of measurement error in the formulation used by Reed and others as fundamental to understanding this paradox.  

> An important tacit assumption in Reed’s analysis, as in the other works referred
to above, is that the recruitment level X is known accurately prior to the harvest decision, [...] In the case of fishery resources, the stock level X is almost never known very accurately, owing to the difficulty of observing fish in their natural environment.

Under such an assumption, uncertainty introduced by stochastic growth is effectively purged by each subsequent observation rather than accumulating, and stock extinction can only occur if the manager explicitly decides to harvest the entire stock.

## Clark's Paradox: M < D

Clark and Kirkwood set out to address this problem by considering the case in which stochastic population growth occurs after population size is measured but before harvest, such that manager must act without perfect knowledge of the current system state.  Unfortunately, this problem proved easier to recognize than to solve, as Clark & Kirkwood recognized at the outset: 

> For reasons of tractability, we shall adopt the simplifying assumption that the escapement level S, is known exactly at the end of that period. (The mathematical difficulty
of the problem increases markedly if this assumption is
relaxed.) 

Rather than resolve Reed's Paradox, this assumption compounds the problem, leading to optimal harvests that are generally even higher (i.e. less cautious) than the analgous deterministic policy.  The same counter-intuitive result can also be found in subsequent work [@Sethi2005] which makes a different but equally limiting simplifying assumption (supplement).  (Both @Clark1986 and @Sethi2005 remark on the counter-intuitive nature of their results)


<!-- 

Clark: 
> The above results appear to contradict the conventional wisdom of renewable resource management, under which high uncertainty would call for increased
caution in the setting of quotas.


Sethi: 
> It may seem counter-intuitive that a measurement error causes lower expected escapements below the deterministic fishery closure threshold.


--> 


## Precautionary approaches

Perhaps recognizing 

## A solution


Here, we explore how uncertainty over the present impacts decisions




We shall focus on examples from fisheries, which have long been both incubator and proving ground for most of our more general theories of ecological management, from the and 

Data are readily avialable and a compartively strong connection between scientific process of stock assessment and the implementation of policy is already established.  It is also an area which, as we will see, though many models already account for uncertainty, decision strategy still reflects fundamentally more deterministic ideas.

Conclusions:

- failing to account for uncertainty properly can lead to erroneous conclusions
- Prior beliefs (reflecting prior observations) matter.









<!-- FIXME: In practice, MSY and Reed are very different -->

<!-- Big picture: fisheries is a foundation and testing ground for conservation
and management. Yet at it's heart lies a controdiction.  -->

<!-- MSY and Constant Escapement -->

Yet fisheries are not managed at their maximum ecological or economic potential.  
Taken as a whole, most ocean fisheries yield a net negative economic return
[@FAO2009], while some 68% of global fisheries are not in good biological condition [@Costello2016].
Nevertheless, fisheries management in both theory and practice are 


In a deterministic world at equilibrium (without economic discounting), 
the policies of constant escapement and maximum
sustainable yield look identical: the stock is maintained at a fixed stock
size or biomass, called $B_{MSY}$ in the MSY/fisheries jargon, which is 
equivalent to the escapement $S^*$ in the optimal control jargon and equal
to half the carrying capacity, or $K/2$, in the familiar Graham-Schaefer 
(logistic growth followed by harvest) model. Likewise, the harvest is identical,
occuring after recruitment and bringing the population back to this optimal
level; an annual harvest of $H_{MSY} = rK/4$ in Graham-Schafer model for either policy.
This similarity disguises significant differences in how the policies behave
when the biomass is either above or below $B_{MSY}$.

<!-- Ways in which constant escapement deviates from MSY -->
The economically optimal amount to harvest when the population is below 
$B_{MSY}$ is zero -- no harvest.  This permits the population to return
as rapidly as possible to the stock size at which it generates the maximum
yield, and thus the maximum economic return.  This result holds even when
recruitment is stochastic and thus future stock sizes are uncertain, 
as rigorously proven by @Reed1979.  Perhaps surprisingly, this is not what
fisheries management thinks of as a maximum sustainable yield (MSY) policy,
and does not reflect how fisheries are managed today. Rather, an MSY policy
is intepreted as fishing at the *effort*, $F_{MSY} = H_{MSY} / B_{MSY}$ that would generate the maximum
sustainable yield if the population was at the optimal biomass, $B_{MSY}$,
*regardless* of the current stock size. It is important to realize this policy
is framed in terms of *effort* $F$: for example, the length of the year open to fishing,
or equivalently, the per-capita mortality rate of fish, and not in terms of harvest, $H$.
A population below $B_{MSY}$ that remains harvested at a constant $H_{MSY}$ will eventually be
driven to extinction, but harvested at a constant $H = F_{MSY} \cdot B$ for $B < B_{MSY}$,
the stock will eventually recover to $B_{MSY}$.  Consequently, this simple policy should
converge to the optimal policy in the long run, assuming there is no uncertainty in
recruitment, measurement, or implementation.  

The economically optimal policy of constant-escapement also differs from MSY
when stocks are above $B_{MSY}$.  As before, the MSY policy continues to assume
a fixed mortality rate, $F_{MSY}$, which should eventually reduce the stock to
the level of $B_{MSY}$.  Also as before, the optimal policy is not so patient --
to derive maximum yield it seeks to return the population to the $B_{MSY}$ not
*eventually*, but as quickly as possible, and thus will recommend a harvest larger
than $H_{MSY}$ to accomplish this. These differences become more salient in the case
of a population under stochastic growth, since the resulting variation leads
to a population that frequently above or below $B_{MSY}$.  The greater responsiveness
of the constant-escapement policy to the current stock size thus necessarily 
results in both the faster recovery of overexploited stocks and higher economic
returns.

The variation in the harvest required to achieve this constant escapement policy
can seem impractical from a top-down management perspective.  However, it is 
important to realize that the application and implications of this policy are
not purely academic. Economists have for some time observed these inherent 
inefficiencies, and argued that the establishment of property rights in fisheries [@Arnason2012].
Approaches such as individual transferable quotas (ITQs) would incentivise
fisheries behavior to converge towards the more dynamic harvests of a constant
escapement policy, as doing so would increase the value of an individual's share.
It is precisely this reasoning which explains the broad patterns of recovery
observed in the landmark paper @Costello2016, which compares future of global
fisheries under a Rights Based Fisheries Mangement (RBFM), fishing at MSY,
and "buisness as usual" (BAU) scenario.  Their analysis assumes that a RBFM
approach should achieve the economically optimal policy of constant-escapement,
which alone explains why RBFM should see both faster recovery and higher 
economic yields than MSY, as we have just described. The substantial detail their
analysis introduces with respect to the dynamics of over 4000 individual stocks
as well as additional economic knock-on effects from managing based on quotas
rather than fishing effort permit them to offer quantitatively precise 
estimates regarding the time required and economic value generated by such
recovery, but are not essential to understand the broad pattern that suggests
that nearly all stocks should recover under either an RBFM or MSY-style 
management, but that the recovery would be fastest and the economic benefits
greatest under the former.  That conclusion was already implicit in how
these models are defined.  Unfortunately, 

-------

Measuring and understanding collapse and over-exploitation of fisheries
world-wide remains an essential issue for the ecological sciences
[@Costello2016].  Effective management practices in marine ecosystems also
inform conservation and resource management in less well-studied
systems. 

<!-- Set up broad relevance of understanding this issue -->




Central to both fisheries research and
policy, including international agreements such as the United Nations
Law of the Sea [@UNCLOS1982], is the principle of  maximal sustainable yield (MSY).
MSY aims to maintain a population at a fixed population size which should result in
the greatest long-term harvest (often referred to as Biomass at MSY,
$B_{MSY}$). While the theory dates back to classic work
of 1950s such as Beverton [@Beverton1957] and Schaefer [@Schaefer1957]
in deterministic models, it is Reed 1979 paper [@Reed1979] which proves
that the intuitive result of the deterministic models remains the optimal
policy for maximizing expected value of a fishery subject to stochastic
growth (i.e. environmental noise). Reed's result has allowed management
to largely sidestep the complexity of optimal control of stochastic
systems.  


This has long begged the question: if stochastic growth can be
safely ignored in determining the optimal harvest, is the same true of
measurement error?  Thanks to recent computational advances for solving
the decision theory problem in the case of imperfect observations
(measurement error), we show that -- contrary to both the intuition
from Reed's result and previous, approximate solutions -- ignoring
measurement error can result in significant over-harvesting, decreased
economic returns, and the potential for complete collapse of the stock.

Some historical perspective is necessary to put this result in the
appropriate context with respect to both management practice as well
as previous research in optimal control of fisheries and other natural
systems under uncertainty.  When population growth
varies stochastically, any fixed annual harvest such as MSY is no longer optimal:
instead, management must respond by dynamically harvesting more in years
of high growth and less in years of low growth.  Reed's proof [@Reed1979]
nevertheless demonstrated that the optimal harvest can still be captured
by a simple rule: harvesting just enough to reduce the population back
down to $B_{MSY}$.  This result is known as a "constant-escapement" policy 
because the population escaping harvest is always the same, 
even while the harvest itself varies dynamically with each stochastic shock. 
Moreover, Reed shows that under some relatively generic assumptions, this escapement
is identical to that predicted by the deterministic theory  ($B_{MSY}$).
Because the optimal harvest policy in the deterministic theory follows directly
from the growth rate (just find the stock size for which recruitment function
is maximized, no need for dynamic programming), attention shifted to inferring
that state equation from data.  Our focus is not on inferring this state
equation, but on the subsequent step of: having done so, how does one determine
the optimal harvest policy while also accounting for measurement uncertainty? 
Previous attempts to address this issue over the past three decades
have relied on various approximations which have usually led to the paradox
that harvests should increase under additional measurement uncertainty, contrary 
to our intuition that we should respond to greater uncertainty with greater caution.
Using more recent optimal control algorithms first developed in the artificial
intelligence literature, we provide a solution which avoids such assumptions
and resolves this paradox in favor of common sense intuition.  

Despite it's generality, Reed's proof makes a subtle assumption which
reduces the the impact uncertainty and underlies his conclusion
that the deterministic intuition of an average MSY is still optimal in 
the stochastic case.
In Reed's construction, the manager measures the stock
size without error during each time step before setting the harvest policy.
An important consequence of this construction is that this model can
thus never lead to accidental extinction of the stock.
Researchers have long recognized the weakness of this assumption of
perfect knowledge of the stock size and have sought to understand how it
may impact the resulting management policy [@Ludwig1981].  Because there is no risk of
accidental extinction in this scenario, it is possible that the optimal
policy may be more aggressive than is warranted.  Unfortunately, due
to the complexity of the analysis required to account for measurement
uncertainty, this question has never been satisfactorily answered.
Moreover, previous attempts at an approximate solution have consistently
found the surprising conclusion that the Reed solution is usually less
aggressive (dictating higher escapement or lower catch quotas) than
attempts to account for measurement uncertainty.  We briefly review the
main results in the ecological and resource economics literature that
have attempted to address this through various approximations before
presenting our solution, which draws on substantial algorithmic advances
that have been made in other fields.

The important way in which perfect observations diminish the role of
uncertainty in the model of Reed [@Reed1979] was first recognized in the classic
work of Clark & Kirkwood [@Clark1986].  They acknowledge the importance of measurement
uncertainty to the optimal solution, while observing that if
this assumption was relaxed, the "difficulty of the problem increases
markedly." Instead, @Clark1986 consider a perfectly observed model in
which harvest takes place after stochastic recruitment but before the
stock is measured, making accidental extinction a possibility
should realized growth fall sufficiently short of expectation.
In this case, @Clark1986 demonstrate that the optimal solution deviates
from the constant escapement rule, with the resulting optimal
policy is often significantly less cautious than the constant escapement policy.
In certain cases, @Clark1986 demonstrate that harvesting to extinction
is actually optimal. Other recent work [@Holden2015; @Johnson2016] has taken 
a similar approach to @Clark1986 in which measurement becomes uncertain due to
stochastic stock dynamics occurring between measurement and harvest, which
can also suggest less conservative (higher harvest) escapement rates. 

Rougharden [@Roughgarden1996] take a complementary approach, introducing measurement
uncertainty but searching only for the optimal constant escapement,
despite presenting no evidence (and indeed contrary to @Clark1986)
that the optimal solution under this circumstance should be a
constant escapement policy. By applying the rule-of-thumb assumption
that the optimal policy can be expressed simply as a constant escapement
(or equivalently, target-stock), the set of possible policies is reduced
dramatically and the calculation is relatively trivial.  As expected,
this restriction results in a policy that is always more conservative (lower harvest) than
the Reed solution which ignores measurement error, but both economically
inefficient and, as we shall see later, still less conservative than
the truly optimal policy for large stocks.   Other studies 
have likewise attempted to include uncertainties in model parameters and measurements
by making this same assumption that a constant escapement solution is optimal and 
thus avoiding solving the full sequential decision optimization problem [@Ludwig1981; @Moxnes2003; @Engen1997].

Sethi et al. [@Sethi2005] seek to address
the limitations of @Roughgarden1996 by searching for the true optimal
policy without the strong assumption of constant escapement.
Like @Clark1986 and others, @Sethi2005 finds support for the counter-intuitive result
of an optimal policy that is significantly less cautious when accounting
for measurement uncertainty than the corresponding constant escapement
solution which ignores it. 
Unfortunately, the approach taken by @Sethi2005 once again avoids solving
the full optimal decision-making problem by means of a simplification
which we might term the amnesic assumption: during each subsequent
decision the manager forgets any previous knowledge of the system.
This allows them to use the standard Stochastic Dynamic Programming
(SDP) solution method used by @Reed1979 and @Clark1986. This method
assumes that problem in question is a Markov Decision Process (MDP):
one in which given the state $x$ and action $a$, the probability of a
transition to state $x'$ is conditionally independent of all previous
states and actions (known as the Markov property).  This holds only if the state
is known without error -- once we introduce any amount of measurement
uncertainty about the state $x$, the process with respect to the observed
state is no longer Markovian but depends on all previous observations.

This problem can be solved by considering
the 'belief' state rather than the observed state, which restores
the Markov property at the cost of much greater problem complexity:
one must consider a (continuously-valued) probability
that the system is in each of the $|X|$ possible states of such a 
Partially Observed Markov Decision Process (POMDP). This is the
key feature of the POMDP approach: all previous observations are
collectively reflected in this belief distribution, and decisions
are based not only on the most recent observation (as in MDP), but
are also influenced by this prior belief.  

The mechanics of 
updating these beliefs, while technical, have been well
illustrated elsewhere even in conservation applications
[e.g. @Lane1989; @Chades2008; @Haight2010; @Chades2011;
@Williams2011; @Springborn2013; @Fackler2014; @Fackler22014; @Baggio2016].
However, these previous studies have relied on relatively direct algorithms 
which are not amenable to the large number of states and actions required by the optimal
fisheries harvest problem.  By leveraging newer point-based algorithms developed in the artificial 
intelligence community [@Kurniawati2008; @Shani2013; see SI; R code], we are able to solve
the POMDP models for fisheries management directly. 
These solutions illustrate how incorporating the information
of all previous observations into a prior belief allows the
POMDP approach to handle measurement error which would 
cause a stock collapse under MDP or deterministic methods.
We also evaluate the performance of proposed method
on a real-world time series of population estimates of
marine ecosystems from RAM Legacy Stock
Assessment Database [@Ricard2011].

## Model formulation

Our formulation of the fisheries management problem closely follows that of 
earlier work [e.g. @Sethi2005], which we summarize here. Alternate formulations are provided in the SI,
illustrating that our conclusions are not constrained to these particular choices.

The fisheries manager seeks to maximize the expected net present value of the fishery
over an infinite time horizon under two sources of uncertainty: population dynamics (i.e. growth of the stock),
and stock measurements, given an model estimate of those dynamics:

\begin{equation}\label{optim}
\max_{\{h_t\} \geq 0} \mathbf{E} \left[ \sum_0^{\infty} \gamma^t U(x_t, h_t) \right]
\end{equation}


The state of the system, $x_t$ corresponds to the (true) fish stock at time $t$. 
The harvest is $h_t = \min \left(x_t,a_t\right)$, where $a_t$ is the attempted harvest at time step $t$.
For simplicity, we assume the reward (utility) is directly proportional to the
harvest, $U(x_t, h_t) = \min(h_t, x_t)$, with future rewards discounted by multiplicative discount factor $\gamma = 0.95$;
alternate harvest functions and alternate discount rate are considered in the SI. 

The population dynamics is formulated as:

\begin{equation}
x_t = \epsilon_{g} f(s_{t-1})
\end{equation}

where $s_{t-1} = x_{t-1} - h_{t-1}$ is the escapement at time $t-1$, and
$\epsilon_{g}$ corresponds to stochastic component of recruitment (growth noise). 

While it is theoretically possible to learn about this model and its parameters during the
decision process itself (so-called adaptive management, e.g. @Johnson2015 for MDP case; 
we discuss the potential for POMDP adaptive management in *Future Directions*), it is
typical to consider that state-space dynamics $f$ have been previously estimated from data.  
The goal of a decision process is to determine the optimal sequence of actions given this
model. From the population dynamics state
equation we derive a set of transition matrices $T(x_t, a_t, x_{t+1})$ describing the
probability of a transition from $x_t$ to $x_{t+1}$ under action $a_t$ (SI Methods).
While such transition matrices can be defined even when $f$ represents only a posterior
distribution of model parameter values [e.g. @Boettiger2015] or an age-structured 
model [e.g. @Holden2015], for simplicity of presentation we will focus on the case
in which $f$ is a fixed model with known parameters, given by the Ricker equation [@Ricker1954]:

\begin{equation}\label{ricker}
f(s_t) = s_t \exp\left(r \left(1-\frac{s_t}{K}\right)\right),
\end{equation}

where $K$ denotes the carrying capacity of the system, and $r$ the growth rate.
The optimal management of this model in the deterministic and growth-noise-only (MDP)
case is already well understood and thus will provide a useful foil against
which to examine the role of measurement uncertainty.  
To demonstrate that our results are not unique to this choice of \eqref{ricker}, two alternate models,
the Beverton-Holt model [@Beverton1957], and the Allen model [@Allen2005], are evaluated in the SI.

The POMDP problem is distinguished by the introduction of measurement error, in which 
the observed stock $z_t$ is measured with uncertainty, $z_t = \epsilon_{m} x_t$. 
In general this is defined by observation matrices $O(z_t, x_t, a_t)$ giving the 
probability of observing $z_t$ given a system in state $x_t$ and having taken action $a_t$,
though in our formulation this probability is independent of the action.

We will assume for simplicity that the stochastic growth noise $\epsilon_g$ and measurement error $\epsilon_m$ 
are distributed log-normally with mean $1$ and scale parameter $\sigma_{g}$ 
and $\sigma_m$ respectively. Larger $\sigma$ corresponds to higher variance,
scaled to be comparable to the uniform noise distribution shown in the SI,
(see *Materials and Methods*).  We evaluate the effect of
different noise levels in both growth and measurements, $\sigma_{g},
\sigma_{m} \in \{0, 0.1, 0.5\}$.

As the numerical solutions of the MDP and POMDP problems require discrete states,
we consider a system of 50 states on a uniform grid of 0 to 1 with $K = 0.66$ and
$r = 1$; (alternative growth rates shown in the SI).   
The transition matrices $T$, together with the observation matrix $O$ and the utility
function, completely specify a POMDP problem which can be solved with a numerical
algorithm (*Materials and Methods*).  




# Results {#results .unnumbered}

To illustrate the impact of measurement error on management outcomes,
we compare two scenarios: with measurement error ($\sigma_m = 0.5$,
see *Materials and Methods*) and without measurement error (Fig \ref{sim}).
In each scenario, we compute the optimal policy using three different
solution methods: POMDP, MDP, and a policy we refer to as Offline POMDP.
In POMDP, the optimal policy at each time point depends not only on the
most recent observation, but on the manager's prior belief of the state,
which depends on all prior observations. As such, the optimal POMDP
policy for a particular observation cannot be computed ahead of time
but must be calculated "online", as observations come in.  In contrast,
in MDP, the optimal policy depends only on the most recent observation.
The "Offline" policy uses the POMDP solution given a fixed, uniform
prior belief, rather than updating the prior belief over states after
each observation.  For each scenario (with and without measurement error), 
we generate 100 simulations of  the fishery being managed under each 
strategy (MDP, Offline, POMDP) for 100 time steps.  We compute the average and standard
deviation of the stock size over these 100 replicates, Fig. \ref{sim},
as well as the mean economic return of each case (Table \ref{Table1})
and the fraction of simulated stocks that have collapsed by the end
of the simulation (Table \ref{Table2}). While we perform these
simulations over a range of models, parameter values and noise distributions, for
simplicity of presentation we focus on simulations
from a Ricker model with log-normally distributed noise (see *Materials and Methods*);
comparable results under the alternative choices are presented in the SI.


\begin{figure}[h]
\centering
\caption{Forward simulations of managing a marine ecosystem under POMDP and MDP models in the presence ( $\sigma_m = 0.5$, top panel) or absence ( $\sigma_m = 0$, bottom panel) of measurement error.  Lines show the mean stock size over 100 replicate simulations, error bands show +/- 1 standard deviation.  Many of the replicate simulations under MDP quickly collapse the stock by over-harvesting when measurement error is present.  In contrast, the POMDP management is robust to the level of measurement error, avoiding stock collapse whether or not measurement error is actually present.  The growth model is Ricker, the noise is log-normally distributed, the carrying capacity of the system is $K = 0.66$, the maximum per capita growth rate is $r = 1$, growth noise is $\sigma_g = 0.5$, and the discount factor is $\gamma = 0.95$.}\label{sim}
\end{figure}

Fig. \ref{sim}, top panel, illustrates that ignoring or underestimating
the measurement error result in dramatic collapse of the stock and
significant loss in revenue: the mean MDP state declines as subsequent
replicate simulations collapse (94/100 collapse within 100 time steps)
when measurement error leads to over-harvesting.  The POMDP method
retains a steady, sustainable harvest that keeps the population below
carrying capacity but results in minimal population collapse (4/100). The
offline solution results in some stock collapse (34/100) as a result of
not updating the manager's belief state over subsequent observations.
Unsurprisingly, average economic returns are also much lower for MDP
when measurement error is present, returning an average of 66% of the net present value returned by
POMDP (Table \ref{Table1}), and would be lower still with less aggressive discounting of future
rewards (Here $\gamma = 0.95$ makes later collapses less relevant to the total).
Fig. S1 shows stock trajectories from several individual replicates, which 
show relatively little decline before collapsing suddenly when managed under MDP
when measurement error is present.  Averaging over an ensemble of such trajectories
gives the appearance of a smooth decline. 

On the other hand, overestimating measurement error might result in a
trivial loss in revenue but does not result in collapse of the stock,
(Fig. \ref{sim}, lower panel). In this scenario, since no
measurement error is present, the MDP solution is indeed optimal, but the
POMDP policy which assumes a measurement error of $\sigma_m = 0.5$ and
thus overestimates the measurement uncertainty performs nearly as well
(average of 94% of the MDP net present value and likewise no collapses of the stock, Table \ref{Table2}).
In the SI we report the same patterns for Ricker model
with uniform noise (Fig. S2), Beverton-Holt model with log-normal noise
(Fig. S3), and Allen model with log-normal noise (Fig. S4).


<!-- Perhaps in-text quotations of these numbers is sufficient?-->


\begin{table}
\centering
\caption{Ecological and economic performance when
measurement error is present, (\(\sigma_m = 0.5\))}
\begin{tabular}{lccc}
& MDP & Offline & POMDP \\
\midrule
Fraction collapsed & 94\% & 34\% & 4\% \\
Economic return & 66\% & 99\% & 100\% \\
\bottomrule
\end{tabular}
\label{Table1}
\end{table}

\begin{table}
\centering
\caption{Ecological and economic performance when
measurement are perfect, (\(\sigma_m = 0\))}
\begin{tabular}{lccc}
& MDP & Offline & POMDP \\
\midrule
Fraction collapsed & 0\% & 0\% & 0\% \\
Economic return & 100\% & 96\% & 94\% \\
\bottomrule
\end{tabular}
\label{Table2}
\end{table}



To facilitate comparison with previous research and management practice,
we plot the corresponding optimal action in terms of *expected escapement*: the
stock the manager expects will be left in the sea after harvest $z_t - h_t$.
Recall that introducing measurement error means that this value can differ
from realized escapement, $x_t - h_t$. Fig. \ref{policy} shows the optimal expected 
escapement as a function of observed stock sizes over a range of growth 
noise and observation error intensities, assuming a uniform prior belief over
states $x_t \in (0,1)$ for $\sigma_m > 0$. These policies are determined numerically
using the SARSOP algorithm for POMDP [ @Kurniawati2008], as discussed in *Materials and Methods* and
illustrated in the supplementary code provided.  

In the MDP case ($\sigma_m = 0$),
we see the classical result of constant escapement [@Reed1979], where the stock is harvested
back down to the same escapement regardless of observed stock or growth noise.
When growth noise is large ($\sigma_g = 0.5$) relative to measurement
error ($\sigma_m = 0.1$), the policy converges towards the the constant
optimal escapement solution of @Reed1979, as expected. These patterns
hold independent of the population growth model (e.g. Beverton-Holt and
Allen) and the shape of the noise distribution (Fig. S5--S6).
The most obvious difference between the MDP and POMDP policies arises in the region of
linear or nearly linear increases in expected escapement occurring at very large observed stock sizes,
which arises from any policy whose harvest remains *constant* over that range. Not increasing
harvest in response to higher observed stock sizes always result in a higher expected escapement, $z_t - h_t$.  
This corresponds to a policy which believes such high observations are almost surely the 
result of measurement error, and suggests that overestimated stock sizes are responsible for MDP
over-harvesting and the subsequent collapse of the stock. At smaller stock sizes, the policies
shown in Fig. \ref{policy} appear more similar over any measurement error, but in fact this is only a consequence of the
uniform prior belief. While Fig. \ref{policy} completely specifies the management policy under MDP,
this is not true for the POMDP solutions ($\sigma_m > 0$), which also depend on all
prior observations through the influence of the belief state.  

\begin{figure}[h]
\centering
\caption{Optimal escapement policy as a function of measured stock for Ricker model, with different measurement errors and growth noise. Noises are log-normally distributed, and the prior belief state is uniform among all stocks. The carrying capacity of the system is $K = 0.66$, the growth rate is $r = 1$ and the discount factor is $\gamma = 0.95$.}\label{policy}
\end{figure}


To illustrate this key difference, we plot (Fig. \ref{bel})
the POMDP policy under two alternative prior belief states: (1) Low
Stock: where the prior belief is centered at $x = 0.2$ , and (2) High Stock:
where the prior belief is centered at the location of carrying capacity $x =
0.66$. This figure is generated in an identical manner to Fig. \ref{policy} 
except for the different choice of prior belief.  Visualizations of these 
prior distributions are shown in Fig. S12. When the prior belief skews towards low stocks, the
probability that an observation of a high stock is an overestimate due to
measurement error is greater, and consequently the policy becomes more conservative
(higher escapement). This ability to incorporate the knowledge from prior
observations accounts for the difference
in performance between the POMDP solution and the Offline solution in
Fig. \ref{sim} when measurement error is present. 
The evolution of the belief state in response to subsequent observations
over a given simulation is shown for the different models in Figs S14 - S16.
Corresponding plots for alternate models are shown in Fig. S9.
The patterns shown here are further robust to the reward function (including
linear cost to harvest and a diminishing returns model, Fig. S8) and the
discount rate Fig. S13. 

\begin{figure}[h]
\centering
\caption{Optimal escapement policy as a function of measured stock and different prior belief states: (1) Uniform: uniform prior belief over all stocks, (2) Low Stock: the prior belief is centered at $x = 0.2$, and (3) High Stock: the prior belief is centered at the location of carrying capacity $x =
0.66$. In this figure, growth model is Ricker, measurement and growth noises are $\sigma_m = \sigma_g = 0.5$, and are log-normally distributed, the growth rate is $r = 1$, and the discount factor is $\gamma = 0.95$.}\label{bel}
\end{figure}


## Application to real-world fisheries

Using historical time series of Argentine Hake on the Patagonian Shelf and
European Plaice on the Celtic-Biscay Shelf from the the RAM Legacy Stock
Assessment database [@Ricard2011], we compare the catch levels recommended
by POMDP and MDP methods against historical values (Fig. \ref{RAM2}). We have selected
these two examples for having both adequately long records and show very
different trends in both population biomass and catch. We non-dimensionalize
the data and then use Maximum
Likelihood Estimation (MLE) through NIMBLE [@nimble-software:2016] to
fit a Ricker model for both these examples (details of MLE fits can be
found in the SI). Based on this model estimate, we then determine MDP
and POMDP policies using the appropriate algorithms.  In the case of MDP,
the optimal harvest is determined directly from that year's estimated
stock abundance.  In the case of POMDP, the optimal harvest depends both
on this stock estimate and the prior belief, which is sequentially updated
based on each previous observation (stock estimate) and action (catch).

Both examples illustrate the contrast between the ignoring (MDP) and accounting for measurement error (POMDP).
The POMDP solution tends to recommend a lower harvest than the MDP solution
in both cases, but not strictly so.  In Plaice example, we see the the POMDP solution is less 
volatile, increasing harvest more modestly in response to observing stock 
sizes while fishing pressure remains constant or increases (e.g. 1980-1990), 
while also decreasing less if stocks decline under constant or decreasing fishing
pressure (e.g. 1990-2000). Under the MDP model, only sharp changes in catch
can drive these sharp shifts in stock levels, while the POMDP model permits that these
can arise in part by measurement error and thus require less volatility in the harvest. 
In the Hake time series, the continued decline of the stock leads both MDP
and POMDP solutions to recommend smaller harvests than historically observed.
Again the POMDP solution is less volatile than the MDP, starting with a more
modest harvest at the beginning of the time-series (where a uniform prior over
states is assumed), and at first decreasing more gradually but then retaining
the moratorium on fishing when a small rebound (circa 2005) leads the MDP to a
renewed harvest.  


\begin{figure}[h]
\centering
\caption{This figure compares the actual stock biomass and catch of European Plaice on the Celtic-Biscay Shelf and Argentine Hake on the Patagonian Shelf with actions suggested by MDP and POMDP frameworks. In the case of POMDP we have used measurement error of $\sigma_m = 0.5$.}\label{RAM2}
\end{figure}


# Discussion {#discussion .unnumbered}

We have shown that fully accounting for measurement error in calculating
the optimal fishing harvest leads to management that is usually more conservative
(higher expected escapement) as the measurement error increases. This
contrasts with the classic solution of constant escapement, in which
larger estimates of the stock size justify proportionally larger harvests.
The importance of our intuitively sensible conclusion is underscored
by the contrast to both much of current fisheries management practice
and previous research into measurement uncertainty.  Most fishing policy
still reflects the results @Reed1979 driven in
the absence of measurement error, and even much previous work on the role
of measurement uncertainty  has either assumed constant escapement-type
solutions [@Roughgarden1996; @Moxnes2003; @Engen1997] or relied on approximations which
have argued that accounting for measurement uncertainty should result
in an *increased* harvest (lower target stock size) [@Ludwig1981; @Clark1986; @Sethi2005].  

Using simulations (Fig. \ref{sim}, S2-S4), we have shown that failing to account for measurement error
can lead to dramatic ecological and economic consequences. MDP solutions, which
ignore measurement error, collapse 94% of simulated time series within 100 time
steps. This does not mean that measurement error in the simulations is so large
as to make informed management impossible -- in fact the optimal POMDP solution,
which accounts for measurement error, experiences a collapse in only 4% of
simulations shown here. While the precise degree of measurement uncertainty may
itself be unknown, these results also show that it is better to overestimate
than underestimate this uncertainty. Even when no measurement error is present,
a POMDP solution which assumes a large measurement error ($\sigma_m = 0.5$) performs
nearly as well as the optimal MDP solution in all of our simulations. Fig. \ref{policy}
and \ref{bel} provide the intuition behind why MDP approach results in such a high probability
of collapse: when measurement error results in a chance over-estimation of the 
stock, the resulting harvest under MDP can be much larger than under POMDP. A single
large or a few consecutive smaller over-estimations of the stock size can thus 
quickly drive the stock to zero.  In contrast, the POMDP solution will harvest
much less under the same observation error, particularly when it compares that
observation against the accumulated prior belief that the current state should
be lower, Fig \ref{bel}.

We have shown that this dramatic reduction in the probability of a 
collapse is not trivially the result of a more cautious strategy; e.g. one which always
harvests less than MDP.  Rather, it is the result of a making full use
of all of the data through the role of the belief state.
The POMDP solution, unlike the MDP solution, depends on
the entire history of previous observations, which inform the current
belief state.  As shown in Fig \ref{bel}, this can correspond
to higher harvests if prior observations give sufficient evidence that 
the stock is higher than suggested by the most recent measurement. As a result,
the POMDP policy can outperform the MDP policy economically as well as 
ecologically. 

We have also demonstrated these patterns by comparing harvests recommended
by MDP methods against those recommended by POMDP methods using two separate
historical time series.  These examples provide a further illustration
of how accounting for measurement uncertainty results in very different policy
outcomes than ignoring it.  Note that this analysis does not seek to explain
the differences between either the MDP and POMDP solutions from the historical
catches actually observed.  While it is very possible that the observed harvests
were governed by some sort of constant-escapement policy, actual catch quotas
or other policy information is not available in this data. Fluctuations in historical
harvest may reflect many other factors than such a policy, such as different stock
models, external constraints such as the cost of adjusting policy [@Boettiger2016], 
or other economic, political or environmental factors.  While we are free to
make comparisons between MDP and POMDP solutions on the historical data, understanding
why historical harvests differed from either of these would need an understanding of 
these contextual issues that are beyond our data and our scope here.
Given the stock-recruitment model for the fishery, the MDP optimum harvest depends only
on the most recent stock estimate, while both the full time series of historical harvests
and historical stock estimates influence the POMDP optimum, by altering the belief
state at the time.  We have
relied on estimating reasonable candidate models and parameters from the time series
a priori (specifically MLE parameters to the Ricker model). Ideally model
and parameters would also be inferred over the course of the sequential decisions,
which would integrate over such uncertainty in models or parameters.
While MDP methods to address these issues of model uncertainty
and parameter uncertainty have been developed elsewhere [e.g. @Johnson2015] this remains
a subject for future research in POMDP applications (see *Future directions*).

We have shown that our result is generally robust to our assumptions:
this pattern holds for differing models (Ricker, Beverton-Holt, and Allen),
differing magnitudes and also different shapes of noise distributions
(log-normal, as considered by @Clark1986 or uniform, as considered by
@Sethi2005), the choice of the reward/profit equation, or the details of
the discretization (see SI).  This robustness is not surprising, being consistent
with sensitivity observed in previous work.  Indeed, in the absence of
measurement error most of these scenarios were already covered by Reed's
proof, (with the exception of the Allen model whose change in concavity
violates the theorem and likewise shows deviations here).
Thus it is perhaps all the more surprising that
constant escapement is not robust to the assumption of measurement error.

The optimization approach considered here can be distinguished from more heuristic
approaches to address the uncertainty, such as pretty good yield (PGY)[@Hilborn2010; @Rindorf2016] or management strategy evaluation (MSE).  Methods based on MSE have been applied in fishery management for providing the decision maker with a rationale to base their decisions given their specific optimization objectives [@Smith1994; @Mapstone2008; @Bunnefeld2011]. The main difference between MSE and methods based on dynamic programming is that MSE does not solve the optimization problem to provide the optimal strategy, rather it evaluates consequences of a set of strategies defined based on management objectives and provides the outcome of those simulations to the decision maker. In that sense, MSE can be compared to the policy evaluation step of optimization in dynamic programming using policy iteration methods [@Sutton1998], while the policy improvement step is being ignored due to computational complexity. With advancements in efficient solving of dynamic programming optimization under several sources of uncertainty [@Shani2013], the traditional MSE approach can be interpreted as an internal step in the optimization process that tries to identify the best management strategy, searching through all viable and possible strategies. MSE can be also compared to Monte Carlo search algorithms within the space of possible policies that the manager can explore and evaluating the policies based on the outcome [@Smith1999]. For example, @Smith1999 evaluates the effect of several sources of uncertainty such as structural and parameter uncertainty in the models, errors in data and observation systems, estimation uncertainty, and management implementation uncertainty in partnership with Australian Fisheries Management Authority.


Our results have important implications for management of fisheries.
The most evident of these is that given the unavoidable realities of measurement
error in stock estimates, the wide use of management based on constant-escapement
solutions and derivative concepts such as maximum sustainable yield (MSY), maximum
sustainable biomass ($B_{MSY}$),
which are central to scientific fisheries management and policy
included the United Nations Law of the Sea [@UNCLOS1982], are insufficient to
guarantee either maximum sustainable economic yield or persistence of fish stocks.
Instead, target harvest or target escapement must reflect current and previous 
stock estimates and the degree of measurement uncertainty present. While precise 
estimates of the uncertainty in measurements, $\sigma_m$ may be difficult to obtain,
we have shown that it better both ecologically (in the probability of stock collapse)
and economically (in the profits from fishing) to overestimate than underestimate this
quantity.


This important qualitative impact that measurement error has on the
optimal solution of an important and well-studied ecological management
problem has more general implications.  The role of measurement error
is most often acknowledged in the breach -- a mathematically
convenient assumption only.  After all, inherent stochasticity has often been found
to make only small differences from deterministic solutions, as @Reed1979
proved in this case. Our result demonstrates how frail such an assumption
regarding measurement uncertainty may be, particularly when determining
optimal policy.  No doubt the mathematical and computational difficulty of
accounting for measurement uncertainty has forestalled greater attention
to this issue.  The growing wave of available data makes such concerns
about measurement error all the more pressing, as imperfect but readily
available observations make such data-driven optimization possible in more
applications. 

These results have both tactical and strategic implications for ecological 
modeling and fisheries management [sensu @May1973]. At a strategic level,
this highlights the danger in ignoring the potentially asymmetric impact of
measurement error, which can lead to significant over-harvesting and potential
collapse of the stock.  At a tactical level, the precise amount by which
harvest should be adjusted to account for a given measurement error to maximize
the expected value of a stock will require a POMDP solution for the specific 
fishery in question, which is now computationally feasible using the approach
we have presented here. We hope that the recent advances in efficient and accurate
POMDP solvers, together with greater attention to these challenges,
will encourage a wider consideration of the role of measurement error
in determining appropriately precautionary management policy.

In conclusion, we have demonstrated the importance of measurement error
in the long-standing question of optimal harvests in fisheries.  We have 
shown that overestimating the measurement error can still result in policies
that are nearly optimal both economically and ecologically, while ignoring or
underestimating the measurement noise can cause dramatic collapses of fish
stocks even when no tipping point is present.  This suggests that the failure
to account for measurement error in this way in even the most advanced 
fisheries management could contribute to long-term trends in declining
stocks [e.g. @Costello2016]. We believe the approach taken
here both highlights the importance of accounting for measurement error and
provides an example of how this can be accomplished in the POMDP framework
using modern algorithms on complex problems. We have also implemented the
proposed method on a real-world problem of managing a marine ecosystem and show
that the policy suggested by POMDP is significantly different with respect to the
actual catch landings.

## Future directions

Several limitations that have been studied in MDP models, such as parameter 
and model uncertainty and adaptive management [e.g. @Johnson2015] remain
intriguing future challenges for POMDP problems. Future work could extend the examples
shown here to include more realistic models, such as those with age structure, as
has only recently been done for the MDP case [@Holden2015].
There remains a need for further improvement of the proposed method to include such model uncertainty. 
Previous attempts that adapt POMDP tools to include model uncertainty [i.e. @Chades2012] have had to
assume full observability of state space, ignoring measurement uncertainty. 
A second limiting assumption common to MDPs and POMDPs is that of stationary dynamics: 
that the population dynamics equation itself is not changing over
time. In reality, forces such as climate change and other forms of environmental variations violate this
assumption. @Fackler22014 attempts to address this problem by 
adaptation of Mixed Observability MDP [@Ong2010] framework, although the proposed algorithm
for finding optimal solution to such non-stationary systems is intractable, except for 
extremely simplified examples used in that study. Our future work involve relaxing
these assumptions by proposing computationally feasible approximate algorithms within the 
POMDP framework to deal both with model uncertainty and non-stationarity of system's dynamics.
Lastly, the introduction of POMDP approaches raises a central question for managers: when is it
worthwhile to actively reduce measurement error to derive a better policy, and when is it
best simply to account for current measurement error?  This issue can be addressed through
a Value of Information framework, as @Johnson2015 illustrates in the case of MDPs.


# Materials and Methods {#methods .unnumbered}

A Partially Observed Markov Decision Process (POMDP) [@Smallwood1973;
@Sondik1978] is a generalization of a Markov Decision Process (MDP),
which is a fundamental model for sequential decision making.  In the
ecological literature, MDPs are often referred to by their solution
method: Stochastic Dynamic Programming [SDP see @Marescot2013].
The MDP approach has been widely used in behavioral ecology
[@Mangel1988] as well as conservation ecology and resource economics
[e.g. @Mangel1985]. Introductions to MDP and solving them through dynamic
programming are provided in @Mangel1985, @Bertsekas1996 and @Sutton1998.
Specifically, POMDPs overcome one of the main limitations of MDP which
is the assumption about the full observability of the system's state.
In POMDP, the exact state of the system cannot be
observed directly, but can be inferred by indirect measurements.
POMDPs can be represented as a probabilistic graphical models
[@Barber2012] as in Fig. S11.  For further details regard POMDP framework,
its parameters, and details of solving the optimization problem,
refer to the SI. 

Our approach utilizes the SARSOP algorithm of @Kurniawati2008. Computational 
requirements are still significantly more demanding than the equivalent MDP solution.
Precise computational time and memory requirements depend not only on system size but on
the precision requested of the approximate, point-based solution. Reasonable
solutions for the problems considered here can be reached within an hour of computation,
though were run for five hours each to confirm convergence. 
As a supplement to this paper we provide example scripts for replicating
the analyses shown here, which can be found at https://github.com/boettiger-lab/sarsop.
