

It is precisely this reasoning which explains the broad patterns of recovery
observed in the landmark paper @Costello2016, which compares future of global
fisheries under a Rights Based Fisheries Mangement (RBFM), fishing at MSY,
and "buisness as usual" (BAU) scenario.  Their analysis assumes that a RBFM
approach should achieve the economically optimal policy of constant-escapement,
which alone explains why RBFM should see both faster recovery and higher 
economic yields than MSY, as we have just described. The substantial detail their
analysis introduces with respect to the dynamics of over 4000 individual stocks
as well as additional economic knock-on effects from managing based on quotas
rather than fishing effort permit them to offer quantitatively precise 
estimates regarding the time required and economic value generated by such
recovery, but are not essential to understand the broad pattern that suggests
that nearly all stocks should recover under either an RBFM or MSY-style 
management, but that the recovery would be fastest and the economic benefits
greatest under the former.  That conclusion was already implicit in how
these models are defined. 



-------------


A fundamental concept to the management of any natural population is the notion of Maximum Sustainable Yield, MSY. The notion of MSY is rooted in the determinstic models dating back to foundational work in resource economics and ecological management half a century ago [@Berverton; @Scheffer].  Though the concept has been the focus of significant criticism for some time [e.g. @Botsford_nature_piece] that ctitique has been largely on the "Maximum" part, while the existence of a "Sustainable Yield."  

## Reed's Paradox: $S = D$

In 1979, a fundamental paper by William Reed [@Reed1979] proved that, under a very general assumptions, the harvest policy for a stochastically fluctuating population was identical to that of the equivalent, deterministic population.  More precisely, Reed shows that the optimal harvest of the stochastically flutuation population should always aim to reduce the population back to a constant size $S$ (termed by Reed as "escapement," while in most fisheries literature uses the term $B_{MSY}$, the biomass at Maximum Sustainable Yield}).  Moreover, this value, $S$, is no more conservative than had we been able to predict future populations with perfect accuracy, as in the determinstic case of constant escapement, $D$.  A notable exception to this result is when the population is not "self-sustaining," that is,
the stochasticity is severe enough to pose an extinction risk to the unhavested population.  In such cases Reed proves there is still a single constant target population size $S$, but that $S > D$, though often by very small amount, reflecting the small probability of a purely chance extinction.  

An important corrolary of this result is that suggested a way to side-step the laborious dynamic programming required to find an optimal policy for stochastic populations: the deterministic solution is found trivially from maximum of the stock-recruitment curve. Thus much subsequent attention has focused on the estimating stock-recruitment, including methods that address considerable uncertainty in the data used for this estimate [@], while largely ignoring the subsequent step of how to determine an optimal policy in light of that uncertainty. 

The lack of any intuitively precautionary response to the introduction of uncertainty did not go unnoticed: in 1986 Clark and Kirkwood first pointed to the absence of measurement error in the formulation used by Reed and others as fundamental to understanding this paradox.  

> An important tacit assumption in Reed’s analysis, as in the other works referred
to above, is that the recruitment level X is known accurately prior to the harvest decision, [...] In the case of fishery resources, the stock level X is almost never known very accurately, owing to the difficulty of observing fish in their natural environment.

Under such an assumption, uncertainty introduced by stochastic growth is effectively purged by each subsequent observation rather than accumulating, and stock extinction can only occur if the manager explicitly decides to harvest the entire stock.

## Clark's Paradox: M < D

Clark and Kirkwood set out to address this problem by considering the case in which stochastic population growth occurs after population size is measured but before harvest, such that manager must act without perfect knowledge of the current system state.  Unfortunately, this problem proved easier to recognize than to solve, as Clark & Kirkwood recognized at the outset: 

> For reasons of tractability, we shall adopt the simplifying assumption that the escapement level S, is known exactly at the end of that period. (The mathematical difficulty
of the problem increases markedly if this assumption is
relaxed.) 

Rather than resolve Reed's Paradox, this assumption compounds the problem, leading to optimal harvests that are generally even higher (i.e. less cautious) than the analgous deterministic policy.  The same counter-intuitive result can also be found in subsequent work [@Sethi2005] which makes a different but equally limiting simplifying assumption (supplement).  Both @Clark1986 and @Sethi2005 remark on the counter-intuitive nature of their results;

> The above results appear to contradict the conventional wisdom of renewable resource management, under which high uncertainty would call for increased
caution in the setting of quotas.

- @Clark1986


> It may seem counter-intuitive that a measurement error causes lower expected escapements below the deterministic fishery closure threshold.

@Sethi2005



## Precautionary approaches

Perhaps recognizing 

## A solution


Here, we explore how uncertainty over the present impacts decisions




We shall focus on examples from fisheries, which have long been both incubator and proving ground for most of our more general theories of ecological management, from the and 

Data are readily avialable and a compartively strong connection between scientific process of stock assessment and the implementation of policy is already established.  It is also an area which, as we will see, though many models already account for uncertainty, decision strategy still reflects fundamentally more deterministic ideas.

Conclusions:

- failing to account for uncertainty properly can lead to erroneous conclusions
- Prior beliefs (reflecting prior observations) matter.




