---
title: "plotting experiments"
author: "Carl Boettiger"
date: "7/4/2018"
output: github_document
---

```{r}
library(tidyverse)
library(here)
library(fs)
```


```{r}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
#dev=c("cairo_pdf", "png")
library(Cairo)
library(hrbrthemes)
library(extrafont)
library(ggthemes)
hrbrthemes::import_plex_sans()
hrbrthemes::import_roboto_condensed()  
extrafont::loadfonts()
ggplot2::theme_set(hrbrthemes::theme_ipsum())
scale_colour_discrete <- function(...) scale_colour_manual(..., values=ptol_pal()(3))

```


```{r}
log_dir <- fs::path(here(), "data/observe_harvest_recruit") # solution files here
sims <- read_csv(file.path(log_dir, "sims.csv"), col_types = "inicnnn")
```

Try showing replicates individually?

 Based on original, still best

```{r}
sims %>%
  mutate(method = fct_recode(method, "MDP" = "CE", "Heuristic" = "TAC")) %>%
  filter(method != "MSY", sigma_g == "0.15", time <= 50) %>%
  filter(sigma_m != "0.1") %>%
  group_by(time, method, sigma_m) %>%
  summarise(mean = mean(state), sd = sd(state)) %>% 
  mutate(sigma_m = as.character(sigma_m)) %>%
  ungroup() ->
fig1_df
```

```{r fig.width=6, fig.height=6}
fig1_df %>%
  ggplot(aes(time, mean, col=method, fill=method)) + 
  geom_line(lwd=1) + 
  facet_wrap(~ sigma_m, labeller = label_bquote(sigma[m] == .(sigma_m)), ncol=1) + 
  theme(legend.position = "bottom") + 
  ylab("Mean biomass") 
```









```{r}
sims %>%
  select(-value) %>%
  filter(method != "MSY", sigma_g == "0.15", time <= 50) %>%
  mutate(method = fct_recode(method, "MDP" = "CE")) %>%
  filter(sigma_m != 0.1, rep %in% 5:20) %>%
  filter(sigma_m > 0.1) %>%
  ggplot(aes(time, state, col=method, group=interaction(rep,method))) + 
  geom_line(alpha= .5) + 
  facet_wrap(~ sigma_m, labeller = label_bquote(sigma[m] == .(sigma_m))) 
```


```{r}
sims %>%
  select(-value) %>%
  mutate(sigma_m = round(sigma_m,2)) %>%
  mutate(sigma_g = round(sigma_g,2)) %>%
  filter(method != "MSY", sigma_g == 0.15, time <= 50) %>%
  mutate(method = fct_recode(method, "MDP" = "CE")) %>%
  filter(sigma_m == 0.15, method == "POMDP", rep %in% 5:20) %>%
  ggplot(aes(time, state, col=method, group=interaction(rep,method))) + 
  geom_line(col = rgb(0.7, 0.1, 0.4, 0.2)) 


```

