name: Docker Actions
on: [push]
jobs:
  my_job: 
    runs-on: ubuntu-latest
    container: rocker/verse:3.6.2
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |-
          installGithub.r --update FALSE clauswilke/ggtext
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render mansucript
        run: |-
          Rscript -e "lapply(fs::dir_ls('manuscript', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"

## remarkably(?), we can use the standard checkout action, actions/checkout@v1
## even inside this Docker container.

